quick start using cookies
bulatbulat48/ru-scrapy-python pull request #7
Opened 2019-07-12 16:47 UTC by derVedro

where to put your cookies magic, the quick hack

2019-07-12 18:20 UTC, serhii73 commented
@derVedro [COOKIES_ENABLED - Default: True](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#cookies-enabled), так что нет смысла прописывать это в `settings.py`

2019-07-15 10:24 UTC, serhii73 commented
LGTM, @bulatbulat48 мерджим?

2019-07-15 12:44 UTC, bulatbulat48 commented
@serhii73 Nope. Unclear.

2019-07-15 13:02 UTC, serhii73 commented
> @serhii73 Nope. Unclear.

Может тогда напишешь @derVedro что ни так с его пр.

2019-07-16 05:37 UTC, derVedro commented
works for me

2019-07-25 12:07 UTC, bulatbulat48 requested changes
Good work. But fix it please.

2019-07-25 12:07 UTC, bulatbulat48 commented on README.md
> +Иногда нужно чтобы паучок прикидывался зарегистрированным пользователем, а процесс автоматической авторизации может быть слишком хитро реализован на странице. В этом случае передача заранее подсмотре
Сожмите пожалуйста описание. И нужно выкинуть слова: паучок, иногда.

2019-07-25 12:07 UTC, bulatbulat48 commented on README.md
> +* В settings.py активируйте ваши DOWNLOADER_MIDDLEWARES, хотя может быть это и лишнее действие.
Не проверенная информация.

2019-07-25 12:38 UTC, serhii73 commented on README.md
> +Иногда нужно чтобы паучок прикидывался зарегистрированным пользователем, а процесс автоматической авторизации может быть слишком хитро реализован на странице. В этом случае передача заранее подсмотре
> Иногда нужно чтобы прикинуться зарегистрированным пользователем, а процесс автоматической авторизации слишком хитро реализован на странице. В этом случае передача заранее подсмотренных после авторизации пользователя в браузере cookies может помочь. Сделать это в лоб быстро:

2019-07-25 12:39 UTC, serhii73 commented on README.md
> +Иногда нужно чтобы паучок прикидывался зарегистрированным пользователем, а процесс автоматической авторизации может быть слишком хитро реализован на странице. В этом случае передача заранее подсмотре
@derVedro https://glvrd.ru/ - через это погоняйте текст

2019-07-26 15:44 UTC, derVedro commented on README.md
> +Иногда нужно чтобы паучок прикидывался зарегистрированным пользователем, а процесс автоматической авторизации может быть слишком хитро реализован на странице. В этом случае передача заранее подсмотре
довольно сильно упростил стену текста. надеюсь это кому поможет при быстром старте.

2019-07-26 15:47 UTC, derVedro commented on README.md
> +* В settings.py активируйте ваши DOWNLOADER_MIDDLEWARES, хотя может быть это и лишнее действие.
какая именно часть?

2019-08-01 09:42 UTC, serhii73 commented on README.md
> +* В settings.py активируйте ваши DOWNLOADER_MIDDLEWARES, хотя может быть это и лишнее действие.
Думаю, что имеется ввиду 

> хотя может быть это и лишнее действие

2019-10-05 17:12 UTC, bulatbulat48 approved these changes
Looks ok.

2019-10-16 10:04 UTC, merged